### ISSUE TITLE
what type of data stored inside 00.txt

### ISSUE THREAD

**Issue by dingxiaoliang33** [leebhoram/OnlineLearningGround#1]
Hello!
This program is very powerful and I want to  try it. I have just come into contact with this.
When I want to run Demo program，I do not know what type of data stored inside "~/Datasets/kitti/poses/00.txt".  It should correspond to which part of the KITTI dataset?
Very much looking forward to your reply!

**Comment by leebhoram** [comment]
Hi, 
the file is 'odometry ground truth poses', which can be found at 
http://www.cvlibs.net/datasets/kitti/eval_odometry.php

Thanks for your interest.

**Comment by dingxiaoliang33** [comment]
Thanks for your help!

**Comment by xiangfengzhuo** [comment]
Hi,
Thanks for your sharing，I have read the corresponding paper“Online Self-Supervised Monocular Visual Odometry for Ground Vehicles”.It's so grate,and i want to know if it‘s useful in an indoor environment? for the Indoor mobile robot.
Very much looking forward to your reply!
